stages:
  - test
  - release

before_script:
  - touch .npmrc
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
  - npm install

test:node10:
  image: gcr.io/help-1272/node:10
  stage: test
  script:
    - npm test -- --coverage-report=text-summary

test:node8:
  image: gcr.io/help-1272/node:8
  stage: test
  script:
    - npm test -- --coverage-report=text-summary

release:
  image: gcr.io/help-1272/node:release8
  stage: release
  script:
    - do-release --publish
  only:
    - master
